site_name: MarsDude.com
theme:
  name: terminal
  palette: dark
nav:
  - Home: index.md
  - About: Contact.md
  - MicroOS: 
    - Introduction: microos/introduction.md
    - Planning updates: microos/planning-update.md
    
