site_name: MarsDude.com
theme:
  name: material
nav:
  - Home: index.md
  - Contact: contact.md
  - MicroOS: 
    - Introduction: microos/introduction.md
    - Planning updates: microos/planning-update.md
    
